spring:
  application:
    name: smart-portfolio-backend

  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}

    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10


  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      show-sql: false


  ai:
    openai:
      api-key: dummy-key-bypass
      audio:
        speech:
          enabled: false
        transcription:
          enabled: false
      image:
        enabled: false
      chat:
        base-url: https://api.groq.com/openai/v1
        api-key: ${GROQ_API_KEY}
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.3

      embedding:
        base-url: https://api.jina.ai/v1
        api-key: ${JINA_API_KEY}
        options:
          model: jina-embeddings-v2-base-en

  vectorstore:
    pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 768
  cache:
    type: caffeine
    cache-names: portfolio_projects, ai_responses
    caffeine:
      spec: maximumSize=100,expireAfterWrite=24h
